dist: trusty
sudo: required
language: ruby
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- cp .env.development .env
services:
- postgresql
- redis-server
rvm:
- 2.4.0
env:
  global:
    - REDIS_PROVIDER=redis://localhost:6379
    - REDIS_URL=redis://localhost:6379
    - REDIS_SESSION_URL=redis://localhost:6379/0/session
cache: bundler
notifications:
  email: false
  webhooks:
    urls:
      - "https://devbot.gottsnack.net/services/hooks/dHJhdmlzY2k"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
