branches:
  only:
    - master
    - dev
dist: trusty
sudo: required
language: ruby
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp .env.development .env
services:
  - postgresql
  - redis-server
rvm:
  - 2.6.6
env:
  global:
    - REDIS_PROVIDER=redis://localhost:6379
    - REDIS_URL=redis://localhost:6379
    - REDIS_SESSION_URL=redis://localhost:6379/0/session
cache: bundler
notifications:
  email: false
  slack:
    rooms:
      secure: MpZ373MqXXsnpczLi03PaPmourTkxjv8RcWGSlwQ57Ugsf5MeCBW+U6C1GoZo8mfXpGiqTU618FMXqUbTvRcXH0t/XagrNevSbjTw9mKVT+WNiRfGTlUOE/Mk0yaIJcK2vwHtJPaSsyU0wCKdb5kDnOA8NEKSTsVPaF3Aalpva1vLvEeMux1gJcEAILolax37ww+32xKOlVTb2VvmaOrw56gtggqtWRuJ3/B/0895GXAEFmck4cVQM1sXdNF706WMNJVDrQDl6d4hQlgTclERf5L+IMwIoZ+W3bev6EACdXevt9WWIxdn2MEOg2Ll8/+nDIIdwfNSb6gkQu1xhKwWm6GZoO3KMbb59EBb1GzEEvdiE2rgK07QXdNja5lbSuXq3Ro4ZqXJMs4rSdKAUiNfDYt9kBU5nyKt48+hP0vV5p2cn3ytRYxoZ7Pt0Ib4Pv+D8DcswqUNUOy1iHszB1IFp3gRpXnyZVx81wB2PH/+a0NjRjRaUTpiRi/KTK2pJg3HEATkmCpvh5IiQfENC0GREoJBW/wI5DjvcMcSlibyCZuLm/80/KSLWqlxGyFMvA0jBiVeUYhkjpuvQSN/XY6A6X4IJzs5CbHlu0i3TE4A+emdd9S8CCDf9icGiU6D8UhX5vpxnfiPOcO3bAK+YHX+M9eDORBbotehJXq2qjfT5g=
    on_success: always
    on_failure: always
    on_start: always
