dist: trusty
sudo: required
language: ruby
before_script:
  - psql -c 'create database preschool_test;' -U postgres
services:
  - docker
  - postgresql
rvm:
- 2.4.0
cache: bundler
notifications:
  pushover:
    api_key:
      secure: gDI6EguxXGcyDf+y6NovKAlbz6gg+orxHSp+lcMTZh8NGCuGMw85dy84gVwjsfSceHb/CUgdgEoVlw/gJjb/UfzrlVxN25VXuXpk5JBJT62VFgsFLLlpBKIFFi+wlBAwQ2T0pANCh/1U6XzhRlxJvzgbyVwIG8mGoUBMPxOEoajjajyll5zX78sC+OpCWoU02/RaIFCDMbFNeVnEvmtXm5x1qPEiUdLFONSZVstgtx++RNYk0Lvfvv/r5N+tv4IsbIph+aHG3P85JcCqvvmP0SnuNnkQo3eFchPNKpT8JivlhM7lnlVeVHlN/ZnB+jA91Yz55dukxGHxEVDHl3kYRpeyfK2X+OSHiYVTR3s5W6fIfxNsYTohMGkOGR2o1eof1YoTcQJAkGncR0QMeHEs62zUgN7f9ctvrEzsTqmZalh3GNev/vC2eKa4yZRqM6X3v/97RAeZTAUfYUOCMGxbS0Q9MH6oj4byEfLu/5VBnKEzBU164SERzEOy7Pc3b9kxF8O+cFD56vFvPG3EFAZ8YQqBikelJepEGSEdoRV3fCQ9MnQtp1QJSCs9pnsnvhpuotuOFy2TtpU3JaptiVJJ+aeIYWMiykjNmT2KNYl0426c8wRlsZwE48CPAieiGVibSPRKhrr4NUYSnKW++va91F6ZU6BaGstuEOXlT6xZ8HQ=
    users:
      secure: qKbQ4ST+z8EAmsy4wM1t0PrvojEyAHwFfLT/RRnQRWrzO9G9PxG+GuSggMc0QS5EAgnyImpxoIAVf2htEtiUtaTvY3yt98kO38sgVZ3PSqpoeK7XMsagHbmny4hvBw8//IDPtDbY8TgwDiXwRFvgXV30TQ1+Oox9AMSzHu3rsmLGa9+LPsEwjr6+ERiVUFgU0DXWe63NBizWz/qgLTF7MwIkFYBLNi2RZhD9BLk2u66yxWBGatgRA1/0ONxHp3bbdCmFigaBopbHMm7OB1z0xa1DkiDZHqqIQ1gWqVu35P3+IVGPzNgrnGC23FHHaBNjZgwZ5f5b/7mUsX9vBLuFt2KQoGmkZ2UxJggFhVoTbaTBjGFL9f0E3LNIJKdCk3lUQX9FAfsMTB6G1cm73itEsbQ0pLt3QZNlAHh4XxgLT4F7GqHASWhrZABhzwW/8sN4qR7m+2dufQC0n7LQT/Mk5HHcoDHGt8Xtku+ALHXSLtATlKMBVYTyyyc08UCEEv78uOh2eCIi/LE747bCp2rsNg3Gx26legPilMi4zWULbmfkKcCaPFLTOF2RgVO1FtcUwBfLYdO6KDtm1c4x0J4RCzqpojOKN3NkLlgcg0q9PwBEjVb9aME1nFxxKFX4sFreSNvQCV/5k4Vj5rgrGb7SxqRFss00CEn8D65zCgy5r+Y=
  email: false
