# DO NOT PUT SECRET VALUES IN THIS FILE. USE THE ENVIRONMENT LUKE

development:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: preschool_development
  pool: <%= ENV['DATABASE_POOL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: postgres
  password:

test:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: preschool_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 25
  port: <%= ENV['DATABASE_PORT'] %>
  username: postgres
  password:

staging:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
