# DO NOT PUT SECRET VALUES IN THIS FILE. USE THE ENVIRONMENT LUKE

development:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: preschool_development
  pool: <%= ENV['DATABASE_POOL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: postgres
  password:

test:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: preschool_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 25
  port: <%= ENV['DATABASE_PORT'] %>
  username: postgres
  password:

staging:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: preschool_staging
  pool: <%= ENV['DATABASE_POOL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: preschool_production
  pool: <%= ENV['DATABASE_POOL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
