# DO NOT PUT SECRET VALUES IN THIS FILE. USE THE ENVIRONMENT LUKE

common: &common
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
